import type { IndexerPreset } from "@/lib/server/indexers/presets";

// Generated from Prowlarr/Indexers definitions/v11 public Cardigann definitions.
// Source: https://github.com/Prowlarr/Indexers/tree/master/definitions/v11
// These are catalog presets. Supported definitions run through the native
// Cardigann adapter; unsupported definitions fail clearly when tested/searched
// instead of being treated as Torznab endpoints.
export const prowlarrPublicIndexerPresets = [
  {
    presetKey: "prowlarr-public-0magnet",
    name: "0Magnet",
    type: "cardigann",
    baseUrl: "https://13mag.net/",
    fetchMode: "direct",
    enabled: false,
    categories: [],
    description: "ØMagnet is a CHINESE Public tracker for Asian 3X (JAV)",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-1337x",
    name: "1337x",
    type: "cardigann",
    baseUrl: "https://1337x.to/",
    fetchMode: "flaresolverr",
    enabled: false,
    categories: [
      "28",
      "78",
      "79",
      "80",
      "81",
      "22",
      "23",
      "24",
      "25",
      "26",
      "27",
      "53",
      "58",
      "59",
      "60",
      "68",
      "69",
      "1",
      "2",
      "3",
      "4",
      "42",
      "54",
      "55",
      "66",
      "70",
      "73",
      "76",
      "5",
      "6",
      "7",
      "41",
      "71",
      "74",
      "75",
      "9",
      "18",
      "19",
      "20",
      "21",
      "56",
      "57",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16",
      "17",
      "43",
      "44",
      "45",
      "46",
      "72",
      "77",
      "82",
      "48",
      "49",
      "50",
      "51",
      "67",
      "33",
      "34",
      "35",
      "36",
      "37",
      "38",
      "39",
      "40",
      "47",
      "52",
    ],
    description:
      "1337x is a Public torrent site that offers verified torrent downloads",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-52bt",
    name: "52BT",
    type: "cardigann",
    baseUrl: "https://www.529074.xyz/",
    fetchMode: "flaresolverr",
    enabled: false,
    categories: ["影视", "音乐", "图像", "文档书籍", "压缩文件", "安装包", "其他"],
    description: "52BT is a CHINESE Public tracker for MOVIES / TV / MUSIC / GENERAL",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-acgrip",
    name: "ACG.RIP",
    type: "cardigann",
    baseUrl: "https://acg.rip/",
    fetchMode: "direct",
    enabled: false,
    categories: [],
    description:
      "ACG.RIP is a CHINESE Public torrent tracker for the latest anime and Japanese related torrents",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-anisource",
    name: "AniSource",
    type: "cardigann",
    baseUrl: "https://asnet.pw/",
    fetchMode: "direct",
    enabled: false,
    categories: ["1"],
    description: "AniSource is a Public site for HD Anime raws.",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-arabtorrents-com",
    name: "arab-torrents.com",
    type: "cardigann",
    baseUrl: "https://arab-torrents.com/",
    fetchMode: "direct",
    enabled: false,
    categories: [
      "14",
      "17",
      "19",
      "22",
      "23",
      "25",
      "26",
      "27",
      "41",
      "44",
      "46",
      "52",
      "56",
      "57",
      "59",
      "65",
      "70",
      "71",
      "86",
      "88",
      "89",
      "90",
      "92",
      "93",
      "98",
      "99",
      "100",
      "101",
      "102",
      "103",
      "113",
      "114",
      "115",
      "116",
      "117",
      "missing1",
    ],
    description:
      "arab-torrents.com is an ARABIC Public Torrent Tracker for MOVIES / TV / GENERAL",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-bangumi-moe",
    name: "Bangumi Moe",
    type: "cardigann",
    baseUrl: "https://bangumi.moe/",
    fetchMode: "direct",
    enabled: false,
    categories: [
      "549ef207fe682f7549f1ea90",
      "54967e14ff43b99e284d0bf7",
      "549cc9369310bc7d04cddf9f",
      "549eef6ffe682f7549f1ea8b",
      "549eefebfe682f7549f1ea8c",
      "549ef015fe682f7549f1ea8d",
      "549ef250fe682f7549f1ea91",
      "549ff1db30bcfc225bf9e607",
    ],
    description: "Bangumi Moe is a Public torrent site for ANIME",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-bigfangroup",
    name: "BigFANGroup",
    type: "cardigann",
    baseUrl: "https://bigfangroup.org/",
    fetchMode: "direct",
    enabled: false,
    categories: [
      "51",
      "12",
      "35",
      "13",
      "52",
      "33",
      "45",
      "48",
      "21",
      "32",
      "39",
      "44",
      "5",
      "28",
      "18",
      "24",
      "36",
      "38",
      "53",
      "54",
      "19",
      "20",
      "31",
      "46",
      "29",
      "49",
      "50",
      "27",
      "9",
      "43",
      "1",
      "11",
      "37",
      "47",
      "55",
      "25",
      "22",
      "26",
      "23",
      "30",
      "42",
      "14",
      "15",
    ],
    description: "BigFANGroup is a RUSSIAN Public Torrent Tracker for MOVIES / TV",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-blueroms",
    name: "BlueRoms",
    type: "cardigann",
    baseUrl: "https://www.blueroms.ws/",
    fetchMode: "direct",
    enabled: false,
    categories: [
      "/arcade",
      "/dreamcast",
      "/gba",
      "/genesis",
      "/neogeo",
      "/3ds",
      "/n64",
      "/nds",
      "/gamecube",
      "/switch",
      "/wii",
      "/wiiu",
      "/ps1",
      "/ps2",
      "/ps3",
      "/ps4",
      "/psp",
      "/psvita",
      "/saturn",
      "/snes",
      "/xbox",
    ],
    description: "BlueRoms is a Public Torrent Tracker for ROMS",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-btetree",
    name: "BT.etree",
    type: "cardigann",
    baseUrl: "https://bt.etree.org/",
    fetchMode: "direct",
    enabled: false,
    categories: [],
    description: "BT.etree is a Public Tracker dedicated to Bootleg FLAC MUSIC",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-btdirectory",
    name: "BTdirectory",
    type: "cardigann",
    baseUrl: "https://btmulu.live/",
    fetchMode: "flaresolverr",
    enabled: false,
    categories: ["Other"],
    description: "BTdirectory (BT目录) is a Public DHT Crawler",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-btstate",
    name: "btstate",
    type: "cardigann",
    baseUrl: "https://btstate.com/",
    fetchMode: "direct",
    enabled: false,
    categories: [],
    description: "btstate is a Public BitTorrent DHT search engine.",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-byrutor",
    name: "Byrutor",
    type: "cardigann",
    baseUrl: "https://byrutgame.org/",
    fetchMode: "direct",
    enabled: false,
    categories: [
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16",
      "248",
      "17",
      "20",
      "18",
      "232",
      "233",
      "19",
      "249",
      "22",
      "25",
      "26",
      "27",
      "28",
      "29",
      "30",
      "31",
      "32",
      "33",
      "34",
      "35",
      "36",
      "37",
      "38",
      "39",
      "40",
      "41",
      "42",
      "43",
      "44",
      "45",
      "48",
      "49",
      "50",
      "51",
      "52",
      "53",
      "58",
      "59",
      "60",
      "61",
      "63",
      "64",
      "65",
      "66",
      "67",
      "68",
      "69",
      "70",
      "71",
      "72",
      "73",
      "74",
      "75",
      "76",
      "77",
      "78",
      "79",
      "80",
      "81",
      "82",
      "83",
      "84",
      "85",
      "86",
    ],
    description: "Byrutor is a RUSSIAN Public Torrent Tracker for GAMES",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-catorrent",
    name: "Catorrent",
    type: "cardigann",
    baseUrl: "https://catorrent.net/",
    fetchMode: "direct",
    enabled: false,
    categories: [
      "PC",
      "PS1",
      "PS2",
      "PS3",
      "PS4",
      "PS5",
      "SWITCH",
      "PSP",
      "PSVITA",
      "XONE",
      "X360",
      "WIIU",
      "WII",
      "3DS",
      "NDS",
      "N64",
      "NGC",
      "DREAMCAST",
      "SAT",
    ],
    description: "Catorrent is a RUSSIAN Public Torrent Tracker for GAMES",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-crackingpatching",
    name: "CrackingPatching",
    type: "cardigann",
    baseUrl: "https://crackingpatching.com/",
    fetchMode: "direct",
    enabled: false,
    categories: [
      "adobe-software",
      "adobe-tools",
      "android",
      "animations-3d-graphics",
      "antivirus",
      "cd-dvd-burners",
      "compression-tools",
      "converters",
      "crack-serials",
      "downloader",
      "drivers-update",
      "games",
      "home",
      "idm",
      "idm-crack-patch",
      "ios-mac-os-x-2",
      "keygen-loader",
      "keygen-serial",
      "microsoft-office",
      "multimedia",
      "other",
      "pdf-tools",
      "photo-editing-tools",
      "recovery-software",
      "request-crack-patch",
      "screen-recorders",
      "security",
      "system-optimizers",
      "uncategorized",
      "vpn",
      "windows",
      "windows-app",
    ],
    description: "CrackingPatching is a Public tracker for Software and Apps",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-damagnet",
    name: "DaMagNet",
    type: "cardigann",
    baseUrl: "https://damag.net/",
    fetchMode: "direct",
    enabled: false,
    categories: ["Other"],
    description: "DaMagNet is a Public DHT Crawler",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-dmhy",
    name: "dmhy",
    type: "cardigann",
    baseUrl: "https://share.dmhy.org/",
    fetchMode: "flaresolverr",
    enabled: false,
    categories: [
      "2",
      "31",
      "3",
      "41",
      "42",
      "4",
      "43",
      "44",
      "15",
      "6",
      "7",
      "9",
      "17",
      "18",
      "19",
      "20",
      "21",
      "12",
      "1",
    ],
    description: "dmhy is a TAIWANESE Public magnet tracker for ANIME",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-ehentai",
    name: "E-Hentai",
    type: "cardigann",
    baseUrl: "https://e-hentai.org/",
    fetchMode: "direct",
    enabled: false,
    categories: ["1"],
    description: "E-Hentai is a Public site for Hentai doujinshi, manga.",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-ebookbay",
    name: "EBookBay",
    type: "cardigann",
    baseUrl: "https://ebb.la/",
    fetchMode: "direct",
    enabled: false,
    categories: [
      "Action/Adventure",
      "Animals",
      "Arts",
      "Audio",
      "Beauty",
      "Business",
      "Certification",
      "Children/Kids",
      "Classic/Literary",
      "Comics",
      "Computer",
      "Contemporary",
      "Cooking",
      "Crafts",
      "Education",
      "Entertainment",
      "Fantasy",
      "Gardening",
      "Health",
      "Historical",
      "History",
      "Horror",
      "Humorous",
      "Internet",
      "Magazine",
      "Marketing",
      "Medical",
      "Mystery/Suspense",
      "Nonfiction",
      "Novel",
      "Other",
      "Paranormal",
      "Political",
      "Real",
      "Reference",
      "Religion",
      "Romance",
      "Sci-Fi",
      "Science",
      "Self-Help",
      "Society",
      "Software",
      "Sports",
      "Technical",
      "Teen/Young",
      "Textbook",
      "Thriller",
      "Travel",
      "Tutorial",
      "Western",
    ],
    description: "EBook Bay (EBB) is a Public Torrent Tracker for E-BOOKS",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-elitetorrent-wf",
    name: "Elitetorrent-wf",
    type: "cardigann",
    baseUrl: "https://www.elitetorrent.wf/",
    fetchMode: "direct",
    enabled: false,
    categories: [],
    description: "Elitetorrent-wf is a SPANISH Public tracker for MOVIES / TV",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-extratorrent-st",
    name: "ExtraTorrent.st",
    type: "cardigann",
    baseUrl: "https://extratorrent.st/",
    fetchMode: "flaresolverr",
    enabled: false,
    categories: [
      "3D",
      "AAC",
      "Adult",
      "Android",
      "Anime",
      "Audio",
      "Bollywood",
      "Comics",
      "DVD",
      "Documentary",
      "Dubbed",
      "Ebooks",
      "English-translated",
      "Episodes",
      "Games",
      "Hentai",
      "Highres",
      "Linux",
      "Live",
      "Lossless",
      "Manga",
      "MP3",
      "MP4",
      "Mac",
      "Magazines",
      "Movie",
      "Movies",
      "Music",
      "NDS",
      "Other",
      "PC",
      "PS3",
      "PS4",
      "PSP",
      "Pictures",
      "Radio",
      "Raw",
      "Season",
      "Software",
      "Sports",
      "Subs",
      "Switch",
      "TV",
      "UltraHD",
      "Video",
      "Wii",
      "Windows",
      "Xbox360",
    ],
    description: "ExtraTorrent.st is a Public tracker for MOVIE / TV / GENERAL magnets",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-eztv",
    name: "EZTV",
    type: "cardigann",
    baseUrl: "https://eztvx.to/",
    fetchMode: "direct",
    enabled: false,
    categories: [],
    description: "EZTV is a Public torrent site for TV shows",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-filemood",
    name: "FileMood",
    type: "cardigann",
    baseUrl: "https://filemood.com/",
    fetchMode: "direct",
    enabled: false,
    categories: [],
    description: "FileMood is a Public BitTorrent DHT search engine.",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-freejavtorrent",
    name: "Free JAV Torrent",
    type: "cardigann",
    baseUrl: "https://www.freejavtorrent.com/",
    fetchMode: "direct",
    enabled: false,
    categories: [],
    description: "Free JAV Torrent is a Public tracker for Asian 3X (JAV)",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-gamestorrents",
    name: "GamesTorrents",
    type: "cardigann",
    baseUrl: "https://www.gamestorrents.app/",
    fetchMode: "direct",
    enabled: false,
    categories: [
      "juegos-pc",
      "juegos-psp",
      "juegos-ps3",
      "juegos-ps4",
      "juegos-ps2",
      "juegos-mac",
      "juegos-xbox360",
      "juegos-wii",
      "juegos-nds",
    ],
    description: "GamesTorrents is a SPANISH Public tracker for GAMES",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-internetarchive",
    name: "Internet Archive",
    type: "cardigann",
    baseUrl: "https://archive.org/",
    fetchMode: "direct",
    enabled: false,
    categories: [
      "audio",
      "etree",
      "movies",
      "image",
      "texts",
      "software",
      "web",
      "collection",
      "account",
      "data",
      "other",
    ],
    description:
      "Internet Archive is a non-profit digital library offering free universal access to books, movies & music, as well as 406 billion archived web pages",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-kickasstorrents-to",
    name: "kickasstorrents.to",
    type: "cardigann",
    baseUrl: "https://kickass.torrentbay.st/",
    fetchMode: "flaresolverr",
    enabled: false,
    categories: [
      "3DMovies",
      "Adult",
      "AdultGames",
      "AdultHentai",
      "AdultMagazines",
      "AdultPictures",
      "AdultVideo",
      "Android",
      "Anime",
      "AnimeAudioLossless",
      "AnimeAudio[Lossless]",
      "AnimeAudio[Lossy]",
      "AnimeEnglish-translated",
      "AnimeLiveAction[English-translated]",
      "AnimeLiveAction[Non-English]",
      "AnimeLiveAction[Raw]",
      "AnimeManga[English-translated]",
      "AnimeManga[Raw]",
      "AnimeMusicvideo",
      "AnimePictures",
      "AnimeRaw",
      "AnimeSubs",
      "Apps",
      "AppsAndroid",
      "AppsLinux",
      "AppsMac",
      "AppsWindows",
      "Audiobooks",
      "Bollywood",
      "Books",
      "BooksAudiobooks",
      "BooksComics",
      "BooksEbooks",
      "BooksManga[English-translated]",
      "BooksManga[Raw]",
      "Comics",
      "DVD",
      "Documentary",
      "DubbedMovies",
      "EBooks",
      "English-translated",
      "Games",
      "GamesNDS",
      "GamesOtherGames",
      "GamesPCGames",
      "GamesPS3",
      "GamesPS4",
      "GamesPSP",
      "GamesWii",
      "GamesXbox360",
      "HighresMovies",
      "Linux",
      "Lossless",
      "MP3",
      "MP4",
      "Mac",
      "Movieclips",
      "Movies",
      "Movies3DMovies",
      "MoviesBollywood",
      "MoviesDVD",
      "MoviesDocumentary",
      "MoviesDubbedMovies",
      "MoviesHighresMovies",
      "MoviesMP4",
      "MoviesMusicvideos",
      "MoviesMovieclips",
      "MoviesOtherMovies",
      "MoviesUltraHD",
      "Music",
      "MusicLossless",
      "MusicMP3",
      "MusicMusicvideos",
      "MusicOthermusic",
      "Musicvideos",
      "NDS",
      "Other",
      "OtherGames",
      "OtherMovies",
      "Othermusic",
    ],
    description:
      "kickasstorrents.to is a Public KickAssTorrent clone for MOVIES / TV / GENERAL",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-kickasstorrents-ws",
    name: "kickasstorrents.ws",
    type: "cardigann",
    baseUrl: "https://kickass.ws/",
    fetchMode: "direct",
    enabled: false,
    categories: [
      "applications",
      "books",
      "games",
      "movies",
      "music",
      "other",
      "tv",
      "xxx",
    ],
    description:
      "kickasstorrents.ws is a Public KickAssTorrent clone for MOVIES / TV / GENERAL",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-knaben",
    name: "Knaben",
    type: "cardigann",
    baseUrl: "https://api.knaben.org/",
    fetchMode: "direct",
    enabled: false,
    categories: [],
    description:
      "Knaben is a Public meta-search engine aggregating many torrent sites via a JSON API",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-limetorrents",
    name: "LimeTorrents",
    type: "cardigann",
    baseUrl: "https://www.limetorrents.fun/",
    fetchMode: "direct",
    enabled: false,
    categories: [
      "TV",
      "Movies",
      "Music",
      "Games",
      "Applications",
      "Other",
      "Anime",
      "E-books",
    ],
    description:
      "LimeTorrents is a Public general torrent index with mostly verified torrents",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-linuxtracker",
    name: "LinuxTracker",
    type: "cardigann",
    baseUrl: "https://linuxtracker.org/",
    fetchMode: "direct",
    enabled: false,
    categories: [
      "0",
      "2002",
      "2004",
      "2289",
      "2012",
      "13",
      "2003",
      "2292",
      "2005",
      "2006",
      "2007",
      "2263",
      "39",
      "2212",
      "2009",
      "2183",
      "2196",
      "2216",
      "2227",
      "2288",
      "56",
      "2252",
      "2260",
      "2219",
      "1231",
      "2237",
      "2272",
      "2017",
      "2301",
      "2243",
      "2275",
      "2286",
      "2020",
      "1238",
      "2262",
      "2283",
      "2021",
      "2022",
      "79",
      "2182",
      "2023",
      "2205",
      "2026",
      "1220",
      "2028",
      "102",
      "1216",
      "2253",
      "2264",
      "2248",
      "107",
      "2257",
      "2037",
      "121",
      "122",
      "2273",
      "2245",
      "2285",
      "123",
      "128",
      "131",
      "2038",
      "2192",
      "2287",
      "144",
      "2226",
      "148",
      "2261",
      "2265",
      "2259",
      "155",
      "2040",
      "2041",
      "161",
      "2042",
      "2278",
      "164",
      "2179",
      "2223",
      "2043",
    ],
    description: "LinuxTracker is a Public Linux ISO Torrent Repository",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-mactorrentsdownload",
    name: "Mac Torrents Download",
    type: "cardigann",
    baseUrl: "https://www.torrentmac.net/",
    fetchMode: "direct",
    enabled: false,
    categories: ["apps", "games", "design-assets", "uncategorized"],
    description: "Mac Torrents Download is a Public tracker for Mac software",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-magnetcat",
    name: "Magnet Cat",
    type: "cardigann",
    baseUrl: "https://magnetcatcat.com/",
    fetchMode: "direct",
    enabled: false,
    categories: ["影视", "音乐", "图像", "文档书籍", "压缩文件", "安装包", "其他"],
    description: "Magnet Cat is a Public Tracker for MOVIES / TV / GENERAL",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-magnetdownload",
    name: "MagnetDownload",
    type: "cardigann",
    baseUrl: "https://www.magnetdownload.com/",
    fetchMode: "direct",
    enabled: false,
    categories: ["Other"],
    description: "MagnetDownload is a Public DHT Crawler",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-megapeer",
    name: "MegaPeer",
    type: "cardigann",
    baseUrl: "https://megapeer.vip/",
    fetchMode: "flaresolverr",
    enabled: false,
    categories: [
      "79",
      "5",
      "174",
      "6",
      "76",
      "89",
      "57",
      "145",
      "55",
      "164",
      "21",
      "94",
      "28",
      "107",
      "41",
      "52",
      "169",
      "178",
    ],
    description: "MegaPeer is a RUSSIAN Public Torrent Tracker for MOVIES / TV",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-mikan",
    name: "Mikan",
    type: "cardigann",
    baseUrl: "https://mikanani.me/",
    fetchMode: "direct",
    enabled: false,
    categories: ["1"],
    description: "Mikan is a CHINESE Public torrent tracker for ANIME",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-mixtapetorrent",
    name: "MixtapeTorrent",
    type: "cardigann",
    baseUrl: "http://www.mixtapetorrent.com/",
    fetchMode: "direct",
    enabled: false,
    categories: [],
    description: "MixtapeTorrent is a Public Music site for MixTapes",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-mypornclub",
    name: "MyPornClub",
    type: "cardigann",
    baseUrl: "https://myporn.club/",
    fetchMode: "flaresolverr",
    enabled: false,
    categories: ["XXX"],
    description: "MyPornClub is a Public Torrent Tracker for 3X",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-nekobt",
    name: "nekoBT",
    type: "cardigann",
    baseUrl: "https://nekobt.to/",
    fetchMode: "direct",
    enabled: false,
    categories: ["5070", "2000"],
    description: "nekoBT is a Public Torrent Tracker for ANIME",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-newstudio",
    name: "NewStudio",
    type: "cardigann",
    baseUrl: "https://newstudio.tv/",
    fetchMode: "direct",
    enabled: false,
    categories: ["6"],
    description: "NewStudio is a RUSSIAN Public site for TV",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-nipponsei",
    name: "Nipponsei",
    type: "cardigann",
    baseUrl: "https://nipponsei.minglong.org/",
    fetchMode: "direct",
    enabled: false,
    categories: ["music"],
    description: "Nipponsei is a Public site for MUSIC fresh from JAPAN",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-noname-club",
    name: "NoNaMe Club",
    type: "cardigann",
    baseUrl: "https://nnmclub.to/",
    fetchMode: "direct",
    enabled: false,
    categories: [
      "48",
      "925",
      "872",
      "724",
      "725",
      "729",
      "731",
      "1345",
      "733",
      "1346",
      "1329",
      "1330",
      "1331",
      "1332",
      "1340",
      "658",
      "890",
      "1336",
      "1337",
      "1338",
      "1339",
      "660",
      "232",
      "734",
      "742",
      "735",
      "738",
      "967",
      "907",
      "739",
      "1109",
      "736",
      "737",
      "898",
      "935",
      "871",
      "973",
      "960",
      "1239",
      "740",
      "741",
      "503",
      "504",
      "506",
      "763",
      "1335",
      "1241",
      "1023",
      "717",
      "509",
      "508",
      "510",
      "1254",
      "1042",
      "511",
      "916",
      "512",
      "561",
      "1284",
      "562",
      "513",
      "514",
      "515",
      "516",
      "517",
      "518",
      "519",
      "520",
      "521",
      "522",
      "523",
      "524",
      "532",
      "533",
      "535",
      "530",
      "529",
      "525",
      "526",
      "527",
    ],
    description:
      "NoNaMe Club (NNM-Club) is a RUSSIAN Public Tracker for MOVIES / TV / MUSIC",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-nyaasi",
    name: "Nyaa.si",
    type: "cardigann",
    baseUrl: "https://nyaa.si/",
    fetchMode: "direct",
    enabled: false,
    categories: [
      "1_0",
      "1_1",
      "1_2",
      "1_3",
      "1_4",
      "2_0",
      "2_1",
      "2_2",
      "3_0",
      "3_1",
      "3_2",
      "3_3",
      "4_0",
      "4_1",
      "4_2",
      "4_3",
      "4_4",
      "5_0",
      "5_1",
      "5_2",
      "6_0",
      "6_1",
      "6_2",
    ],
    description:
      "Nyaa is a Public torrent site focused on Eastern ASIAN media including anime, manga, literature and music",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-onejav",
    name: "OneJAV",
    type: "cardigann",
    baseUrl: "https://onejav.com/",
    fetchMode: "flaresolverr",
    enabled: false,
    categories: [],
    description: "OneJAV is a Public tracker for ASIAN 3X (JAV)",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-opensharing",
    name: "OpenSharing",
    type: "cardigann",
    baseUrl: "https://opensharing.org/",
    fetchMode: "direct",
    enabled: false,
    categories: [
      "6",
      "7",
      "8",
      "9",
      "11",
      "36",
      "37",
      "38",
      "39",
      "12",
      "13",
      "14",
      "15",
      "28",
      "27",
      "26",
      "19",
      "21",
      "20",
      "29",
      "30",
      "35",
      "32",
      "33",
      "40",
      "34",
      "64",
      "65",
      "68",
      "66",
      "67",
      "83",
      "105",
      "84",
      "86",
      "87",
      "85",
      "61",
      "62",
      "63",
      "2",
      "3",
      "18",
      "4",
      "10",
      "5",
      "110",
      "112",
      "113",
      "114",
      "116",
      "115",
      "117",
      "16",
      "43",
      "17",
      "46",
      "41",
      "45",
      "44",
      "47",
      "49",
      "109",
      "99",
      "106",
      "53",
      "54",
      "48",
      "55",
      "56",
      "60",
      "98",
      "51",
      "50",
      "57",
      "52",
      "107",
      "58",
      "104",
      "59",
    ],
    description: "OpenSharing is a RUSSIAN Public Torrent Tracker for 3X",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-pandacd",
    name: "PandaCD",
    type: "cardigann",
    baseUrl: "https://pandacd.io/",
    fetchMode: "direct",
    enabled: false,
    categories: ["3000", "3010", "3040"],
    description:
      "PandaCD is a Public Tracker for MUSIC (Creative Commons and artist-permitted content)",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-pctorrent",
    name: "PC-torrent",
    type: "cardigann",
    baseUrl: "https://pc-torrents.games/",
    fetchMode: "direct",
    enabled: false,
    categories: ["1"],
    description: "PC-torrent is a RUSSIAN Public Torrent Tracker for Games",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-plugintorrent",
    name: "plugintorrent",
    type: "cardigann",
    baseUrl: "https://plugintorrent.com/",
    fetchMode: "direct",
    enabled: false,
    categories: [],
    description: "plugintorrent is a Public site for AUDIO apps, plugins and samples",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-pornotorrent",
    name: "PornoTorrent",
    type: "cardigann",
    baseUrl: "https://pornotorrent.com.br/",
    fetchMode: "direct",
    enabled: false,
    categories: ["XXX"],
    description: "PornoTorrent is a BRAZILIAN Public Torrent Tracker for 3X",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-pornrips",
    name: "PornRips",
    type: "cardigann",
    baseUrl: "https://pornrips.to/",
    fetchMode: "direct",
    enabled: false,
    categories: [],
    description: "PornRips is a Public site for 3X",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-postman",
    name: "Postman",
    type: "cardigann",
    baseUrl: "http://tracker2.postman.i2p/",
    fetchMode: "direct",
    enabled: false,
    categories: [
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "8",
      "9",
      "10",
      "24",
      "11",
      "17",
      "20",
      "21",
      "22",
      "23",
      "13",
      "14",
      "15",
      "16",
      "18",
      "19",
    ],
    description: "Postman is a Public I2P Torrent Tracker for MOVIES / TV / GENERAL",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-rintornet",
    name: "RinTor.NeT",
    type: "cardigann",
    baseUrl: "https://www.rintor.net/",
    fetchMode: "direct",
    enabled: false,
    categories: [
      "27",
      "20",
      "1",
      "12",
      "30",
      "9",
      "10",
      "24",
      "22",
      "26",
      "29",
      "23",
      "21",
      "17",
      "19",
      "28",
      "25",
      "16",
      "11",
      "14",
      "13",
      "15",
    ],
    description: "RinTor.NeT is a RUSSIAN Public tracker for 3X",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-rutor",
    name: "RuTor",
    type: "cardigann",
    baseUrl: "https://rutor.info/",
    fetchMode: "direct",
    enabled: false,
    categories: ["1", "2", "3"],
    description: "RuTor is a RUSSIAN Public site for MOVIES / TV / GENERAL",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-sexypics",
    name: "Sexy-Pics",
    type: "cardigann",
    baseUrl: "https://www.sexy-pics.us/",
    fetchMode: "flaresolverr",
    enabled: false,
    categories: [],
    description: "Sexy-Pics is a Public Magnet Links site for 3X MP4",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-shanaproject",
    name: "Shana Project",
    type: "cardigann",
    baseUrl: "https://www.shanaproject.com/",
    fetchMode: "direct",
    enabled: false,
    categories: ["Anime"],
    description: "Shana Project is a Public torrent site for ANIME",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-showrss-yml",
    name: "showRSS",
    type: "cardigann",
    baseUrl: "https://showrss.info/",
    fetchMode: "direct",
    enabled: false,
    categories: ["1", "2"],
    description:
      "showRSS is a service that allows you to keep track of your favorite TV shows",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-skidrowrepack",
    name: "SkidrowRepack",
    type: "cardigann",
    baseUrl: "https://skidrowrepack.com/",
    fetchMode: "direct",
    enabled: false,
    categories: [
      "9",
      "10",
      "21",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16",
      "17",
      "18",
      "19",
      "20",
    ],
    description: "SkidrowRepack is a Public Torrent Tracker for GAMES",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-sosulki",
    name: "sosulki",
    type: "cardigann",
    baseUrl: "https://sosulki.hlom.ru/",
    fetchMode: "direct",
    enabled: false,
    categories: [
      "12",
      "77",
      "78",
      "79",
      "80",
      "81",
      "75",
      "456",
      "76",
      "70",
      "67",
      "68",
      "69",
      "73",
      "65",
      "66",
      "71",
      "74",
    ],
    description: "sosulki is a RUSSIAN Public Torrent Tracker for 3X",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-sukebeinyaasi",
    name: "sukebei.nyaa.si",
    type: "cardigann",
    baseUrl: "https://sukebei.nyaa.si/",
    fetchMode: "direct",
    enabled: false,
    categories: ["1_0", "1_1", "1_2", "1_3", "1_4", "1_5", "2_0", "2_1", "2_2"],
    description:
      "sukebei.nyaa is a Public torrent site focused on adult Eastern ASIAN media including anime, manga, games and JAV",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-solidtorrents",
    name: "Solid Torrents",
    type: "cardigann",
    baseUrl: "https://solidtorrents.to/",
    fetchMode: "direct",
    enabled: false,
    categories: [],
    description:
      "Solid Torrents is a Public DHT meta-search engine with a JSON API for MOVIES / TV / GENERAL",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-thepiratebay",
    name: "The Pirate Bay",
    type: "cardigann",
    baseUrl: "https://thepiratebay.org/",
    fetchMode: "direct",
    enabled: false,
    categories: [
      "100",
      "101",
      "102",
      "103",
      "104",
      "199",
      "200",
      "201",
      "202",
      "203",
      "204",
      "205",
      "206",
      "207",
      "208",
      "209",
      "210",
      "211",
      "212",
      "299",
      "300",
      "301",
      "302",
      "303",
      "304",
      "305",
      "306",
      "399",
      "400",
      "401",
      "402",
      "403",
      "404",
      "405",
      "406",
      "407",
      "408",
      "499",
      "500",
      "501",
      "502",
      "503",
      "504",
      "505",
      "506",
      "507",
      "599",
      "600",
      "601",
      "602",
      "603",
      "604",
      "605",
      "699",
    ],
    description:
      "The Pirate Bay (TPB) is the galaxy’s most resilient Public BitTorrent site",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-therarbg",
    name: "TheRARBG",
    type: "cardigann",
    baseUrl: "https://therarbg.com/",
    fetchMode: "direct",
    enabled: false,
    categories: [],
    description:
      "TheRARBG is a Public RARBG-successor torrent index for MOVIES / TV / GENERAL",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-tokyotosho",
    name: "Tokyo Toshokan",
    type: "cardigann",
    baseUrl: "https://www.tokyotosho.info/",
    fetchMode: "direct",
    enabled: false,
    categories: [
      "1",
      "10",
      "3",
      "8",
      "2",
      "9",
      "7",
      "4",
      "12",
      "13",
      "14",
      "11",
      "15",
      "5",
    ],
    description: "Tokyo Toshokan is a Public BitTorrent Library for JAPANESE Media",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-torrentdownloads",
    name: "Torrent Downloads",
    type: "cardigann",
    baseUrl: "https://www.torrentdownloads.pro/",
    fetchMode: "direct",
    enabled: false,
    categories: ["8", "4", "5", "3", "7", "1", "2", "9", "0", "6"],
    description:
      "Torrent Downloads (TD) is a Public torrent site for all kinds of content",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-torrentoyunindir",
    name: "Torrent Oyun indir",
    type: "cardigann",
    baseUrl: "https://0.torrentoyunindir.com/",
    fetchMode: "flaresolverr",
    enabled: false,
    categories: [],
    description: "Torrent Oyun indir is a TURKISH Public torrent site for GAMES",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-torrent-pirat",
    name: "torrent-pirat",
    type: "cardigann",
    baseUrl: "http://www.torrent-pirat.com/",
    fetchMode: "direct",
    enabled: false,
    categories: [
      "1",
      "6",
      "7",
      "8",
      "9",
      "11",
      "36",
      "37",
      "38",
      "39",
      "12",
      "13",
      "14",
      "15",
      "28",
      "27",
      "26",
      "19",
      "21",
      "20",
      "29",
      "30",
      "35",
      "32",
      "33",
      "40",
      "34",
      "64",
      "65",
      "68",
      "66",
      "67",
      "83",
      "105",
      "84",
      "86",
      "87",
      "85",
      "61",
      "62",
      "63",
      "2",
      "3",
      "18",
      "4",
      "10",
      "5",
      "110",
      "112",
      "113",
      "114",
      "116",
      "115",
      "16",
      "43",
      "17",
      "46",
      "41",
      "45",
      "44",
      "47",
      "49",
      "109",
      "99",
      "106",
      "53",
      "54",
      "48",
      "55",
      "56",
      "60",
      "98",
      "51",
      "50",
      "57",
      "52",
      "107",
      "58",
      "104",
      "59",
    ],
    description: "torrent-pirat is a RUSSIAN Public Torrent Tracker for 3X",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-torrentby",
    name: "torrent.by",
    type: "cardigann",
    baseUrl: "https://torrent.by/",
    fetchMode: "direct",
    enabled: false,
    categories: [],
    description: "torrent.by is a BELARUSIAN Public Torrent Tracker",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-torrentcore",
    name: "Torrent[CORE]",
    type: "cardigann",
    baseUrl: "https://torrentcore.xyz/",
    fetchMode: "flaresolverr",
    enabled: false,
    categories: [
      "0DAY",
      "DVDR",
      "EBOOK",
      "FLAC",
      "GAMES",
      "MP3",
      "MP4",
      "PDA",
      "PS3",
      "TV",
      "TV-DVDRIP",
      "TV-X265",
      "TV-XVID",
      "UNKNOWN",
      "X264",
      "XBOX360",
      "XVID",
      "XXX",
      "XXX-0DAY",
      "XXX-IMGSET",
      "XXX-X264",
      "XXX-X265",
    ],
    description: "Torrent[CORE] is a Public DHT Crawler",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-torrent9",
    name: "Torrent9",
    type: "cardigann",
    baseUrl: "https://www6.torrent9.to/",
    fetchMode: "flaresolverr",
    enabled: false,
    categories: [
      "films",
      "series",
      "musique",
      "ebook",
      "logiciels",
      "jeux-pc",
      "other",
    ],
    description: "Torrent9 is a FRENCH Public site for MOVIES / TV / GENERAL",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-torrentdownload",
    name: "TorrentDownload",
    type: "cardigann",
    baseUrl: "https://www.torrentdownload.info/",
    fetchMode: "direct",
    enabled: false,
    categories: [
      "Adult",
      "AdultPornHDVideo",
      "AdultPornPictures",
      "AdultPornVideo",
      "Anime",
      "AnimeEnglishtranslated",
      "AnimeAnimeOther",
      "Applications",
      "ApplicationsAndroid",
      "ApplicationsWindows",
      "AudioBooks",
      "AudioAudiobooks",
      "AudioLossless",
      "AudioMusic",
      "BooksAcademic",
      "BooksComics",
      "BooksEbooks",
      "BooksEducational",
      "BooksMagazines",
      "BooksFiction",
      "BooksNonfiction",
      "BooksTextbooks",
      "Ebooks",
      "Games",
      "GamesWindows",
      "Movies",
      "MoviesAction",
      "MoviesConcerts",
      "MoviesCrime",
      "MoviesDocumentary",
      "MoviesDubbedMovies",
      "MoviesHighresMovies",
      "MoviesMusicvideos",
      "MoviesThriller",
      "Music",
      "MusicHardrock",
      "MusicMp",
      "MusicFLAC",
      "MusicLossless",
      "MusicRB",
      "MusicTranceHouseDance",
      "Other",
      "OtherEbooks",
      "OtherComics",
      "OtherTutorials",
      "OtherUnsorted",
      "PicturesPicturesOther",
      "PicturesWallpapers",
      "Software",
      "TV",
      "TVBBC",
      "TVEllenDeGeneres",
      "TVOther",
      "TVshows",
      "Television",
      "VideoMobile",
      "VideoMovies",
      "VideoMusic",
      "XXX",
      "XXXVideo",
      "XXXHDVideo",
      "XXXPictures",
    ],
    description: "TorrentDownload is a Public torrent meta-search engine",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-torrentgalaxyclone",
    name: "TorrentGalaxyClone",
    type: "cardigann",
    baseUrl: "https://torrentgalaxy.one/",
    fetchMode: "direct",
    enabled: false,
    categories: [
      "Anime",
      "Apps",
      "Books",
      "Docus",
      "Games",
      "Movies",
      "Music",
      "Other",
      "TV",
      "XXX",
      "Documentaries",
      "E-books",
    ],
    description: "TorrentGalaxyClone is a Public site for MOVIES / TV / GENERAL",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-torrentkitty",
    name: "TorrentKitty",
    type: "cardigann",
    baseUrl: "https://www.torrentkitty.cam/",
    fetchMode: "flaresolverr",
    enabled: false,
    categories: [],
    description: "TorrentKitty is a Public torrent indexer",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-torrentproject2",
    name: "TorrentProject2",
    type: "cardigann",
    baseUrl: "https://torrentproject2.net/",
    fetchMode: "direct",
    enabled: false,
    categories: ["Other"],
    description: "TorrentProject2 is a Public torrent meta-search engine",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-torrentqq",
    name: "TorrentQQ",
    type: "cardigann",
    baseUrl: "https://torrentqq418.com/",
    fetchMode: "flaresolverr",
    enabled: false,
    categories: ["adt", "ani", "etc", "gme", "med", "mov", "mus", "spo", "utl"],
    description: "TorrentQQ (토렌트큐큐) is a Public KOREAN tracker for Korean media.",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-torrentsome",
    name: "Torrentsome",
    type: "cardigann",
    baseUrl: "https://torrentsome247.com/",
    fetchMode: "flaresolverr",
    enabled: false,
    categories: [
      "해외영화",
      "한국영화",
      "해외드라마",
      "한국드라마",
      "예능·오락",
      "다큐·교양",
      "음악",
      "유아·어린이",
      "애니메이션",
      "만화",
      "넷플릭스",
    ],
    description: "Torrentsome is a KOREAN Public tracker for Korean media.",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-torrenttip",
    name: "Torrenttip",
    type: "cardigann",
    baseUrl: "https://torrenttip228.top/",
    fetchMode: "flaresolverr",
    enabled: false,
    categories: [
      "한국영화",
      "해외영화",
      "해외드라마",
      "한국드라마",
      "넷플릭스",
      "예능·오락",
      "다큐·교양",
      "스포츠",
      "음악",
      "유아·어린이",
      "유튜브",
      "애니메이션",
      "만화",
      "게임",
      "모바일",
      "유틸리티",
      "전자북·강좌",
    ],
    description: "Torrenttip (토렌트팁) is a Public KOREAN tracker for Korean media.",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-u3c3",
    name: "U3C3",
    type: "cardigann",
    baseUrl: "https://u3c3.com/",
    fetchMode: "direct",
    enabled: false,
    categories: [
      "國產原创",
      "U3C3",
      "Video",
      "Photo",
      "Book",
      "Game",
      "Software",
      "Other",
    ],
    description: "U3C3 is a CHINESE Public tracker focused on 3X Eastern Asian media",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-uindex",
    name: "Uindex",
    type: "cardigann",
    baseUrl: "https://uindex.org/",
    fetchMode: "direct",
    enabled: false,
    categories: ["1", "2", "3", "4", "5", "6", "7", "8", "0"],
    description: "Uindex is a Public Torrent Tracker for MOVIES / TV / MUSIC / GENERAL",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-vsttorrents",
    name: "VST Torrentz",
    type: "cardigann",
    baseUrl: "https://vsttorrentz.net/",
    fetchMode: "direct",
    enabled: false,
    categories: [],
    description: "VST Torrentz is a Public site for AUDIO apps, plugins and samples",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-vsthouse",
    name: "VSTHouse",
    type: "cardigann",
    baseUrl: "https://vsthouse.ru/",
    fetchMode: "direct",
    enabled: false,
    categories: [],
    description:
      "VSTHouse is a RUSSIAN Public site for AUDIO apps, plugins and samples",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-vstorrent",
    name: "VSTorrent",
    type: "cardigann",
    baseUrl: "https://vstorrent.org/",
    fetchMode: "direct",
    enabled: false,
    categories: [],
    description: "VSTorrent is a Public site for AUDIO apps, plugins and samples",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-world-torrent",
    name: "World-torrent",
    type: "cardigann",
    baseUrl: "https://www.darkfox2.cc/",
    fetchMode: "direct",
    enabled: false,
    categories: [
      "Films",
      "Animes",
      "Documentaires",
      "Séries",
      "Musiques",
      "Ebooks",
      "Livres",
      "Logiciels",
      "Applications",
      "Jeux-PC",
      "Jeux-Consoles",
      "Porno",
      "Spectacles",
      "Sports",
      "Formations",
      "Vidéos",
    ],
    description: "World-torrent is a FRENCH Public site for MOVIES / TV / GENERAL",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-xxxclub",
    name: "XXXClub",
    type: "cardigann",
    baseUrl: "https://xxxclub.to/",
    fetchMode: "flaresolverr",
    enabled: false,
    categories: ["0", "1", "2", "4", "3", "5", "6", "7"],
    description: "XXXClub is a Public torrent site for 3X",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-xxxtor",
    name: "xxxtor",
    type: "cardigann",
    baseUrl: "https://xxxtor.com/",
    fetchMode: "direct",
    enabled: false,
    categories: ["XXX"],
    description: "xxxtor is a RUSSIAN Public Torrent Tracker for 3X",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-yts",
    name: "YTS",
    type: "cardigann",
    baseUrl: "https://yts.bz/",
    fetchMode: "direct",
    enabled: false,
    categories: ["45", "44", "46", "47"],
    description: "YTS is a Public torrent site specialising in HD movies of small size",
    requiresApiKey: false,
  },
  {
    presetKey: "prowlarr-public-zamundarip",
    name: "Zamunda RIP",
    type: "cardigann",
    baseUrl: "https://zamunda.rip/",
    fetchMode: "direct",
    enabled: false,
    categories: [
      "1000",
      "1050",
      "2000",
      "2040",
      "2030",
      "2010",
      "2020",
      "2050",
      "2060",
      "3000",
      "3010",
      "3020",
      "3040",
      "4000",
      "4050",
      "4030",
      "4020",
      "4010",
      "4040",
      "4070",
      "5000",
      "5070",
      "5030",
      "5040",
      "5020",
      "5060",
      "6000",
      "6040",
      "7000",
      "7030",
      "8000",
    ],
    description:
      "Zamunda RIP is a BULGARIAN Public Torrent Archive for MOVIES / TV / GENERAL",
    requiresApiKey: false,
  },
] satisfies IndexerPreset[];
